### ISSUE TITLE
Cannot find the PhantomJS.EXE file

### ISSUE THREAD

**Issue by luke-hill** [yaauie/cliver#22]
Breakout Case of https://github.com/yaauie/cliver/issues/19 for Windows Machines on Normal Ruby (Issue previously was for JRuby)

When running tests I get the error:
```
Cliver::Dependency::NotFound: Could not find an executable at given path 'C:/Webdrivers for RubyMine/phantomjs.EXE'.If this path was not specified explicitly, it is probably a bug in [Cliver](https://github.com/yaauie/cliver/issues).
```

- This is on a Windows machine (Win7), running Ruby on RubyMine trying to do Automation.
- All the remedies by elcubo and yauiie have so far not worked. However the Monkeypatch does then allow me to use poltergeist.
- I only have Cliver `0.3.2` in my Gemfile / .lock

One possible issue is it wants phantomJS to have an upper case `.EXE`
**SYSTEM PATH:**

` C:\Ruby22\bin`

**ENV PATH:**
```
C:\ProgramData\Oracle\Java\javapath; 
C:\Program Files (x86)\Intel\iCLS Client\;
C:\Program Files\Intel\iCLS Client\;
%SystemRoot%\system32;
%SystemRoot%;
%SystemRoot%\System32\Wbem;
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;
C:\Program Files (x86)\Skype\Phone\;
C:\Webdrivers for RubyMine\;
C:\Webdrivers;
%android_home%\platform-tools\;
C:\Program Files (x86)\Brackets\command
```

Luke

**Comment by yaauie** [comment]
I'll need a little more info in order to debug and/or duplicate your setup to dive in deeper

1. are you specifying that path to phantomjs explicitly? it does not appear to be part of your `PATH`
2. when you execute `c:/utils/phantomjs-2.1.1-windows/bin/phantomjs.EXE --version` in a shell, what output and exit code to you receive?
3. what version of Windows are you running?
4. what version of Ruby are you running?
5. what method did you use to install Ruby? you mentioned that you're using RubyMine, so did you use a Ruby bundled with RubyMine, or did you provide your own? does "Normal Ruby" mean MRI?

As mentioned in #19 and the cliver project README, you can tell cliver to not bother verifying the version of the executable by setting the [`CLIVER_NO_VERIFY`](https://github.com/yaauie/cliver#get-out-of-my-way-cliver) environment variable (there should be no need to apply the monkey-patch).

**Comment by luke-hill** [comment]
1) In Webdrivers for RubyMine I have `phantomjs`
2) That path doesn't exist. *Is it expecting this path to contain phantom? because it's contained at C:\Webdrivers for RubyMine\phan.......*
3) Win7 SP1
4) Ruby 2.2.4p230
5) Installer from Official site for 2.2.4p230. RubyMine is just my IDE to run tests.

How would I set this variable? As in would I just have a line in my setup files that says
`CLIVER_NO_VERIFY`
??

Sorry for hassle. Thanks for help

**Comment by luke-hill** [comment]
Running your shell command on the correct directory literally returns the following.

```
Shell line
2.1.1
newline
```

**Comment by yaauie** [comment]
In your bug report, you said:

> When running tests I get the error:
> ```
> Cliver::Dependency::NotFound: Could not find an executable at given path 'c:/utils/phantomjs-2.1.1-windows/bin/phantomjs.EXE'.If this path was not specified explicitly, it is probably a bug in [Cliver](https://github.com/yaauie/cliver/issues).
> ```

Since  `c:/utils/phantomjs-2.1.1-windows/bin` is not on your `PATH`, the only way cliver would look there is if something in your code (or in another library you use) explicitly told cliver to look there, something like:

~~~ ruby
Cliver.assert('c:/utils/phantomjs-2.1.1-windows/bin/phantomjs.EXE', '~>2.1')
~~~

Since there is no executable there, it makes sense that cliver is failing to find one.

In order to allow cliver to find the best-match executable on your `PATH`, you'll need to change it to something like the following; cliver will then identify _all_ executables with the given name that exist on your path, and select one that matches the version constraints:

~~~ ruby
Cliver.assert('phantomjs', '~>2.1')
~~~

*******

In your case, setting the `CLIVER_NO_VERIFY` environment variable would not help, since cliver would still attempt to validate that an executable exists at the given explicit path, and you're telling me that one does not.

**Comment by yaauie** [comment]
Since it appears as though you're using poltergeist, I've dug in a step further:

Poltergeist's client takes an optional [`:path`](https://github.com/teampoltergeist/poltergeist/blob/v1.11.0/lib/capybara/poltergeist/client.rb#L36) as an optional way to explicitly provide a path to a phantomjs executable; you should omit this option when initializing your client.

**Comment by luke-hill** [comment]
Can you show me where I'd set the Cliver.assert command, is that something that needs to be done in the Gemfile? or in the suite?

**Comment by luke-hill** [comment]
Ok I'm an idiot, I copied the error from #19. My error is:

```
Cliver::Dependency::NotFound: Could not find an executable at given path 'C:/Webdrivers for RubyMine/phantomjs.EXE'.If this path was not specified explicitly, it is probably a bug in [Cliver](https://github.com/yaauie/cliver/issues).
./features/support/hooks.rb:23:in `Before'
```

**Comment by alij** [comment]
Is there any update on this. I am getting the following error for JRuby:

`Could not find an executable at given path 'C:/ProgramData/Chocolatey/bin/phantomjs.EXE'.If this path was not specified explicitly, it is probably a bug in [Cliver](https://github.com/yaauie/cliver/issues). (Cliver::Dependency::NotFound)
  ./features/support/hooks.rb:2:in `Before'`

The location is in my path as well:
` where phantomjs
C:\ProgramData\Chocolatey\bin\phantomjs.exe`

**Comment by luke-hill** [comment]
updates to this if you're interested.

The issue was that `command_found = true` was coming through but `@std_err` was a huge string and `@std_out` was `''`. Whereas it was expecting `@std_out` to be `2.1.1` and `@std_err` to be `''`.

The offending lines were the `Open3.popen3` bit where it was ascertaining the values of `i,o,e`. I'm not sure how much more help I can be as the monkeypatch values are different to the ones being obtained (Which I obviously expected). So something in the calculation of these values is going awry.

**Comment by luke-hill** [comment]
Closing issue to reduce overhead. Phantom not really a use-case for me anymore.
